### ISSUE TITLE
Hello Andy

### ISSUE THREAD

**Issue by willdoescode** [ThetaHacks/thetahacks2021#1]
nothing more to say

**Comment by KaiDevrim** [comment]
Hello I am the new director of ThetaHacks

**Comment by willdoescode** [comment]
I am too

**Comment by willdoescode** [comment]
`if (thetahacks.exists()) { will.isdirectornowthankyou() }`

**Comment by KaiDevrim** [comment]
This issue will be escalated past the directors and owners.

**Comment by willdoescode** [comment]
All the way up to the cia

**Comment by KaiDevrim** [comment]
No to god, idiot.

**Comment by willdoescode** [comment]
which god?

**Comment by KaiDevrim** [comment]
Depends, how do you pronounce gif.

**Comment by willdoescode** [comment]
like g-i-f

**Comment by KaiDevrim** [comment]
with g like in green or g like j

**Comment by willdoescode** [comment]
like g

**Comment by KaiDevrim** [comment]
please report back with a recording of you saying gif.

**Comment by willdoescode** [comment]
ok

**Comment by theAnshulGupta** [comment]
ok

**Comment by theAnshulGupta** [comment]
damn github hid my comment

**Comment by willdoescode** [comment]
why

**Comment by liqyn** [comment]
huh what is happening

**Comment by theAnshulGupta** [comment]
cuz it says 1 similar comment

**Comment by theAnshulGupta** [comment]
so toxic

**Comment by willdoescode** [comment]
andy responded finally

**Comment by theAnshulGupta** [comment]
aight imma close?

**Comment by willdoescode** [comment]
not if i close first
